language: objective-c
before_install:
 - export LANG=en_US.UTF-8
 - brew upgrade xctool
 - gem install cocoapods
 - pod install
script:
 - xctool -workspace 'GreedDB.xcworkspace' -scheme ‘Example’ -configuration Debug -sdk iphonesimulator clean build test ARCHS=i386 VALID_ARCHS=i386 ONLY_ACTIVE_ARCH=NO 
